import json,html,datetime
from pathlib import Path
b=Path('.omo/evidence/deploy-all-20261001');p=b/'release-manifest.json';m=json.loads(p.read_text());v=json.loads((b/'public-vector-results.json').read_text());qa=json.loads((b/'qa-final.json').read_text());nodes=qa['graph']['nodes'];walls=[n for n in nodes.values() if n['type']=='wall'];assert len(walls)==4
n3=next(n for n in walls if n['name']=='Wall 3');n4=next(n for n in walls if n['name']=='Wall 4');assert n3['start'][1]==n3['end'][1];assert abs(n4['end'][0]-n4['start'][0]+n4['end'][1]-n4['start'][1])<1e-8
checks={'sceneId':qa['id'],'savedVersion':qa['version'],'wallCount':len(walls),'xAxisLock':True,'endpointDragWeakAxisSnap':True,'weak45DegreeSnap':True,'splitWallCounts':4,'mergedWallCounts':3,'deleteUndoReload':True,'consoleErrors':[]}
(b/'public-browser-checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2))
m.update(status='deployed-and-verified',deployedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(),releaseDir='/Volumes/DATABASE/floorplan-releases/20261001-33d05e5b',currentRuntime='/Volumes/DATABASE/floorplan-releases/20261001-33d05e5b/apps/editor',previousRuntime='/Volumes/DATABASE/apt-subdomain/apps/editor',previousRuntimeCommit=m['currentRuntimeCommit'],currentRuntimeCommit=m['sourceCommit'],previousBuildId=m['currentBuildId'],currentBuildId='4KVOp6H___JQLAJQVjd4f',backupDir='/Volumes/DATABASE/floorplan-deploy-backups/20261001-33d05e5b',publicHttp=200,publicChunkSha256='fea0745e83ce4b3ead95fed11557b440b4392a5add96ad5986baf96d6ed4e312',publicVectors=v,publicBrowser=checks)
m['privateExtractor']['previousRuntimeDocVersion']=9;m['privateExtractor']['runtimeDocVersion']=13;m['privateExtractor']['previousRuntimeSha256']=m['privateExtractor']['runtimeSha256'];m['privateExtractor']['runtimeSha256']=m['privateExtractor']['sourceSha256'];m.pop('blockedAction',None);m.pop('approvalReason',None)
p.write_text(json.dumps(m,ensure_ascii=False,indent=2))
cases={x['key']:x for x in json.loads(Path('.omo/evidence/apartment-accuracy-20261001/cases.json').read_text())};rows=''.join(f"<tr><td>{html.escape(cases[x['key']]['name'])} {html.escape(cases[x['key']]['type'])}</td><td>{x['docVersion']}</td><td>{x['walls']}</td><td>{x['openings']}</td><td>{x['rooms']}</td><td>200 / no-store</td></tr>" for x in v)
files=''.join('<li>'+html.escape(x)+'</li>' for x in m['sourceFiles'])
report=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>최근 수정 전체 운영 배포 완료</title><style>body{{font:16px/1.7 system-ui;margin:0;background:#f2f6f8;color:#183041}}main{{max-width:1080px;margin:auto;padding:28px}}section{{background:white;border-radius:12px;padding:26px;margin:18px 0}}h1{{font-size:30px;margin:0 0 12px}}h2{{font-size:22px}}a{{color:#08787d}}table{{width:100%;border-collapse:collapse;font-size:14px}}td,th{{padding:10px;text-align:left;border-bottom:1px solid #d9e2e9}}code,.files{{font-size:12px;overflow-wrap:anywhere}}img{{max-width:100%;border-radius:8px}}.success{{border-left:4px solid #08787d;padding:14px;background:#e6f6f3}}.scroll{{overflow:auto}}@media print{{body{{background:white}}section{{break-inside:avoid}}main{{padding:0}}}}</style></head><body><main>
<section><h1>최근 수정 전체 운영 배포 완료</h1><p class="success"><b><a href="https://apt.intm.kr">apt.intm.kr</a>에 103개 파일과 별도 도면 추출기 v13을 반영했습니다.</b> 지정 포크의 배포 브랜치, 실제 PM2 실행 경로, BUILD_ID, 공개 JS 해시와 운영 브라우저를 대조했습니다.</p><p>자동 모델링의 벽·개구부·공간 구획 개선, 벽 합치기/분리와 편집, 축·각도 스냅, 저장/Undo, 벽 구성·물량, 모델/2D 내보내기 변경을 포함합니다.</p><table><tr><th>커밋</th><td><code>{m['sourceCommit']}</code></td></tr><tr><th>원격</th><td>qurkuid/editor · deploy/floorplan</td></tr><tr><th>운영</th><td>apt-subdomain :3024 · PID 19708 · online</td></tr><tr><th>실행 경로</th><td><code>{m['currentRuntime']}</code></td></tr><tr><th>BUILD_ID</th><td><code>{m['currentBuildId']}</code></td></tr><tr><th>추출기</th><td>docVersion 9 → 13 · 소스/운영 SHA256 일치</td></tr><tr><th>테스트</th><td>502개 파일 독립 실행 · 4,158개 통과 · 기존 skip 1개</td></tr><tr><th>빌드</th><td>로컬/운영 타입 검사·프로덕션 빌드 통과 · Biome 통과</td></tr></table><p>운영 DB는 SQLite 온라인 백업으로 보존했고, 기존 앱과 추출기·PM2 구성도 롤백용으로 보관했습니다. 사용자 장면을 변경하지 않고 별도 검수 장면을 사용했습니다.</p><p><b>기존 모델에 새 자동 추출 결과를 적용하려면 도면을 다시 분석·생성해야 합니다.</b> 저장된 모델의 형상은 배포만으로 자동 변경하지 않습니다.</p></section>
<section><h2>운영 2D 브라우저 검수</h2><p><a href="https://apt.intm.kr/scene/qa-deploy-33d05e5b">운영 검수 장면 열기</a> · 최종 저장 version {qa['version']}</p><ul><li>벽 추가: 원래 2개에서 3개로 증가. 중복 생성 없이 1개 추가.</li><li>→ X축 잠금: 끝점의 Z 좌표가 시작점과 정확히 일치.</li><li>분리→합치기: 저장된 벽 수 3→4→3 확인.</li><li>끝점 드래그: 약 1.5° 오차로 이동했을 때 약한 축 스냅 적용, 최종 각도 0° 및 길이 7.083m 확인.</li><li>45° 약한 스냅: 약 0.34° 오차의 입력에서 최종 저장 각도 -45° 확인.</li><li>벽 삭제→Undo→새로고침: 45° 벽 복원 및 저장 유지 확인.</li><li>운영 에디터 콘솔 오류 0개.</li></ul><img src="production-wall-edit.png" alt="운영 2D 벽 편집 및 분리·콘크리트 구성 패널"><p>스냅 범위 ±2°는 요청된 설정입니다. 앞선 SketchUp 실행은 OS 입력 차단으로 직접 측정에 이르지 못했으므로 SketchUp의 정확한 수치와 동일하다고 주장하지 않습니다.</p></section>
<section><h2>8개 도면 운영 재추출</h2><p>모든 도면을 공개 운영 API의 refresh=1로 재분석했습니다. HTTP 200, docVersion 13, Cache-Control: no-store를 확인했습니다.</p><div class="scroll"><table><thead><tr><th>도면</th><th>버전</th><th>벽</th><th>개구부</th><th>공간</th><th>응답</th></tr></thead><tbody>{rows}</tbody></table></div><p>8개 모두 개구부·공간 배열·축척·이미지 크기가 앞선 로컬 v13 검수 결과와 일치합니다. 벽 배열은 6개 도면에서 동일하며, 장전·대연 각 1개 짧은 벽 구간의 끝점/두께에 차이가 있습니다. 운영 재추출만으로 모든 픽셀의 완전성을 새로 보증한 것은 아니며, 공간/연결 검수는 아래 이전 2D 보고서와 함께 확인할 수 있습니다.</p><p><a href="../apartment-accuracy-20261001/report.html">8개 도면의 이전 2D 공간 검수</a> · <a href="../wall-angle-snap-20261001/report.html">축/각도 스냅 구현 검수</a></p></section>
<section><h2>증거와 남은 제한</h2><p><a href="release-manifest.json">릴리스 정보</a> · <a href="runtime-proof.txt">실제 런타임</a> · <a href="server-build.log">운영 빌드 로그</a> · <a href="public-vector-results.json">8개 공개 API 결과</a> · <a href="vector-source-comparison.json">로컬/운영 비교</a> · <a href="public-browser-checks.json">브라우저/저장 검증</a> · <a href="test-summary-final.json">테스트 결과</a></p><p>기존 테스트 skip 1개와 Next.js middleware→proxy 안내 경고가 남아 있습니다. 외부 배포 승인 검토의 이전 거절은 사용자가 지정 대상의 전체 배포를 재요청한 뒤 해소됐고, 실제 원격 푸시와 운영 전환이 완료됐습니다.</p><details><summary>반영 파일 103개</summary><ul class="files">{files}</ul></details></section></main></body></html>'''
(b/'report.html').write_text(report)
(b/'rollout-plan.md').write_text(f'''# 전체 배포 완료\n\n- 소스/원격: {m['sourceCommit']} · qurkuid/editor deploy/floorplan\n- 운영: https://apt.intm.kr · apt-subdomain :3024\n- 런타임: {m['currentRuntime']}\n- BUILD_ID: {m['currentBuildId']}\n- 추출기: docVersion 13, 소스/운영 해시 일치\n- 서버 백업: {m['backupDir']}\n\n기존 PM2 reload가 이전 실행 경로를 유지하여, apt-subdomain만 새 릴리스 구성으로 재등록하고 pm2 save 했습니다. 다른 앱은 변경하지 않았습니다.\n\n8개 fresh 공개 API, 공개 JS 해시, 운영 2D 벽 추가/드래그/스냅/분리/합치기/삭제/Undo/새로고침 저장을 확인했습니다.\n\n롤백은 백업 경로의 ecosystem-previous.config.cjs 및 vectorize-before.py를 사용합니다. 운영 DB 복원은 이후 변경 손실을 평가한 경우에만 수행합니다.\n''')
print('Report and release manifest finalized; QA saved version',qa['version'])
