export const MODELING_AGENT_MANUAL = [
  '# Pascal Modeling Agent Manual',
  '',
  'Read this manual before every modeling task. It is the shared operational contract for the in-editor modeling agent and agents controlling Pascal through MCP.',
  '',
  '## Start Here',
  '',
  '1. Identify the execution surface: internal structured-plan agent or external MCP agent.',
  '2. Read the current structured scene. Never infer scene truth from viewport pixels.',
  '3. Resolve the exact target from stable node ids, face ids, selection, and hierarchy.',
  '4. Prefer the narrowest semantic operation that expresses the requested change.',
  '5. Apply one logical user gesture as one undoable mutation.',
  '6. Validate the scene, inspect the resulting state, and verify undo for destructive or topology-changing work.',
  '',
  '## Scene Contract',
  '',
  '- X/Z are the ground plane, Y is up, lengths are metres, and rotations are radians.',
  '- Preserve node ids, parent relationships, Body vertex/edge/loop/face ids, face materials, and UV frames unless the requested operation explicitly replaces them.',
  '- Levels belong to Buildings. Walls, zones, slabs, ceilings, roofs, stairs, Bodies, and floor items belong to a Level or their documented structural parent. Doors and windows belong to a Wall.',
  '- For doors and windows, use `t` or `position` from 0 to 1 along the wall unless the operation schema explicitly documents another coordinate.',
  '- Prefer semantic tools and deterministic operations over raw graph patches. Use a raw patch only when no semantic operation represents the change.',
  '- Keep previews ephemeral. Commit only the final result, once.',
  '- Do not silently invent dimensions, geometry, openings, materials, or unsupported topology. Ask for the smallest missing measurement when it changes the result materially.',
  '',
  '## Internal Modeling Agent',
  '',
  '- The editor injects this entire manual, the current scene, selection, relevant schemas, and conversation into every request.',
  '- Return only the structured modeling plan requested by the editor. Do not call tools or edit repository files.',
  '- Use create/update/delete for ordinary nodes. Updates contain changed fields only.',
  '- Use `pushPullBodyFace` for exact Body face extrusion, `transformBody` for Body translation/Y rotation/uniform scale, and `paintBodyFace` for a face material.',
  '- Use `makeMaterialSeamless` for cached seamless texture processing.',
  '- Use `createRoundedRectangularFrameBody` for the supported rounded hollow frame and `createFurniture` plus the furniture bay/tier operations for deterministic cabinet work.',
  '- Validate the whole plan before application. If one patch is invalid, do not partially apply the plan.',
  '',
  '## MCP Agent',
  '',
  '1. Read `pascal://agent-guide` at the beginning of the task, then read `pascal://scene/current/summary` or query only the target nodes.',
  '2. Call `get_session_context` before mutating. For a new project, call `create_project`; for an existing project, call `open_project` with its id. One MCP server session has one explicit active project binding.',
  '3. Use `create_house_from_brief` for fast generation; it creates a project when none is active and otherwise replaces the explicitly active project. `create_from_template` follows the same active-project rule when saving. For precise work use semantic construction, room, opening, furnishing, placement, and query tools.',
  '4. Use `apply_patch` only for exact bulk edits or capabilities without a semantic MCP tool. Do not rely on internal AI-to-MCP automatic dispatch.',
  '5. Save browser-visible progress with `save_scene` and `saveMode: "draft"`. Use `saveMode: "checkpoint"` only for a meaningful milestone.',
  '6. `get_project_status` is read-only and never activates a project. Use `open_project` when a different project must become active.',
  '7. Finish with `validate_scene`, `verify_scene`, `get_project_status`, and `get_session_context`. Return the exact `editorUrl` from tool output.',
  '8. When live-sync reports a version conflict, reload the scene before retrying. Never overwrite a newer graph blindly.',
  '',
  '## Direct Editor Interactions',
  '',
  "- Body Move normally detects another element's horizontal surface and places the moving Body on it. Hold Alt to force free movement and allow deliberate overlap.",
  "- Push/Pull can snap to other elements' faces, edges, and points. Typed distances use the shared unit-aware length input.",
  '- Programmatic agents do not simulate pointer gestures. Express the same final state with deterministic operations and explicit coordinates.',
  '',
  '## Completion Check',
  '',
  '- The requested geometry exists at the intended dimensions and hierarchy.',
  '- `validate_scene` succeeds and `verify_scene.hasIssues` is false, or remaining limitations are stated precisely.',
  '- The mutation is visible in the editor and undo restores the prior state when the operation is undoable.',
  "- External agents return the final `editorUrl`; the internal agent returns a concise message in the user's language plus the smallest valid patch set.",
  '',
  '## Keeping This Manual Current',
  '',
  'Any change that adds or changes a modeling operation, MCP tool/resource/prompt, node capability, interaction modifier, unit rule, validation rule, or AI control path must update this manual in the same change. Remove obsolete instructions instead of accumulating compatibility advice. Tests must prove that both the MCP resource and the internal modeling prompt still expose the current manual.',
].join('\n')
