export const MODELING_AGENT_MANUAL = [
  '# Pascal Modeling Agent Manual',
  '',
  'Read this manual before every modeling task. It is the shared operational contract for the in-editor modeling agent and agents controlling Pascal through MCP.',
  '',
  '## Start Here',
  '',
  '1. Identify the execution surface: internal structured-plan agent or external MCP agent.',
  '2. Read the current structured scene. Never infer scene truth from viewport pixels.',
  '3. Resolve the exact target from stable node ids, face ids, selection, and hierarchy.',
  '4. Prefer the narrowest semantic operation that expresses the requested change.',
  '5. Apply one logical user gesture as one undoable mutation.',
  '6. Validate the scene, inspect the resulting state, and verify undo for destructive or topology-changing work.',
  '',
  '## Scene Contract',
  '',
  '- X/Z are the ground plane, Y is up, lengths are metres, and rotations are radians.',
  '- Preserve node ids, parent relationships, Body vertex/edge/loop/face ids, face materials, and UV frames unless the requested operation explicitly replaces them.',
  '- Levels belong to Buildings. Walls, zones, slabs, ceilings, roofs, stairs, Bodies, and floor items belong to a Level or their documented structural parent. Doors and windows belong to a Wall.',
  '- For doors and windows, use `t` or `position` from 0 to 1 along the wall unless the operation schema explicitly documents another coordinate.',
  '- Prefer semantic tools and deterministic operations over raw graph patches. Use a raw patch only when no semantic operation represents the change.',
  '- Keep previews ephemeral. Commit only the final result, once.',
  '- Do not silently invent dimensions, geometry, openings, materials, or unsupported topology. Ask for the smallest missing measurement when it changes the result materially.',
  '',
  '## Internal Modeling Agent',
  '',
  '- The editor injects this entire manual, the current scene, selection, relevant schemas, and conversation into every request.',
  '- Return only the structured modeling plan requested by the editor. Do not call tools or edit repository files.',
  '- Use create/update/delete for ordinary nodes. Updates contain changed fields only.',
  '- Use `imprintBodyFace` on an eligible closed Body face with a coplanar line/rectangle/circle profile. Include its optional signed `distance` to create a raised boss or recessed pocket atomically without guessing the generated inset face id; omit it for a flat split. Use `pushPullBodyFace` directly for exact existing Body face extrusion, `offsetBodyFace` for a signed planar face-profile offset, `transformBody` for Body translation, arbitrary-axis rotation, positive XYZ scale, and pivot, `paintBodyFace` for a face material, and `sweepBodyFace` for a baked Body-local line-profile sweep along an open or closed planar path.',
  '- Use `offsetBodyFace` only for a closed planar line-edged Body face with no source inner loops. The signed distance in metres is canonical: `distance > 0` performs a nested outward offset and `distance < 0` performs an inward offset. Apply the deterministic miter rule at every corner. Inward offset preserves the source ring and creates one inset face; nested outward offset requires exactly one reciprocal coplanar enclosing host face, preserves the host outer region, and creates one annular face. Preserve the source-region materials and UV frames plus all stable existing ids, and return a deterministic topology remap for created and split features. Reject zero or non-finite distance, a missing face, invalid Body topology, open topology or a non-closed solid, an invalid outer loop, and non-planarity before offset construction. Also reject source inner loops, referenced non-line curves, missing or ambiguous hosts, exterior outward offsets, contact with or crossing of the host boundary or any sibling hole, parallel or collinear degenerate joins, collapse, reversed winding, and self-intersection. Do not trim, repair, or choose another host.',
  '- The canonical Body operation ids are `pushPullBodyFace`, `imprintBodyFace`, `offsetBodyFace`, `transformBody`, `paintBodyFace`, and `sweepBodyFace`; read `pascal://modeling/operations` for their typed input fields, canonical metres/radians, preview, commit, and supported surfaces. Return `op offsetBodyFace` or `op sweepBodyFace` with the exact manifest fields and do not invent a second operation enum.',
  '- Use `sweepBodyFace` only for one open, hole-free, convex, line-edged planar profile and finite Body-local path points. The first path point lies on the profile plane and the first segment is parallel to the profile normal; later stations form a planar piecewise-linear path. Repeat the first station to close it. Curves, holes, concave profiles, non-planar paths, zero-length or reversing segments, self-intersections, and invalid miters are rejected atomically. `pathPoints` are metres; the result is baked, deterministic, and carries a topology remap. The direct editor exposes Follow Path only in 3D; internal AI and MCP use the same canonical operation.',
  '- Use `makeMaterialSeamless` for cached seamless texture processing.',
  '- Use `createRoundedRectangularFrameBody` for the supported rounded hollow frame and `createFurniture` plus the furniture bay/tier operations for deterministic cabinet work.',
  '- Validate the whole plan before application. If one patch is invalid, do not partially apply the plan.',
  '',
  '## MCP Agent',
  '',
  '1. Read `pascal://agent-guide` at the beginning of the task, then read `pascal://scene/current/summary` or query only the target nodes.',
  '2. Call `get_session_context` before mutating. For a new project, call `create_project`; for an existing project, call `open_project` with its id. One MCP server session has one explicit active project binding.',
  '3. Use `create_house_from_brief` for fast generation; it creates a project when none is active and otherwise replaces the explicitly active project. `create_from_template` follows the same active-project rule when saving. For precise work use semantic construction, room, opening, furnishing, placement, and query tools.',
  '4. Use `apply_patch` only for exact bulk edits or capabilities without a semantic MCP tool. Do not rely on internal AI-to-MCP automatic dispatch.',
  '5. Save browser-visible progress with `save_scene` and `saveMode: "draft"`. Use `saveMode: "checkpoint"` only for a meaningful milestone.',
  '6. `get_project_status` is read-only and never activates a project. Use `open_project` when a different project must become active.',
  '7. Finish with `validate_scene`, `verify_scene`, `get_project_status`, and `get_session_context`. Return the exact `editorUrl` from tool output.',
  '8. When live-sync reports a version conflict, reload the scene before retrying. Never overwrite a newer graph blindly.',
  '9. Before any Body semantic edit, read `pascal://modeling/operations`; call `preflight_modeling_operation` with a canonical operation id, the exact Body `nodeId`, and its typed `input` (`faceId` plus signed distance/profile/path, transform fields, or material). Preflight dispatches the manifest operations exhaustively and changes neither scene nor history.',
  '10. Commit a validated Body operation with `commit_modeling_operation` using the same operation id, node id, and typed input boundary. A successful commit applies exactly one logical update, creates one undo step, publishes live sync, and for paint stores the SceneMaterial together with its `scene:` face ref; an invalid request returns structured diagnostics without mutation.',
  '',
  '## Direct Editor Interactions',
  '',
  '- Selecting or re-clicking any scene element is inert: selection alone never starts movement or another modeling gesture. Move an element only after explicitly choosing Move from its action menu or pressing the Move shortcut. A selected Body likewise requires the explicit 3D action menu to arm Rotate, Scale, Push/Pull, Offset, or Follow Path; later face and point clicks belong only to that armed action.',
  '- In 3D, Body Move follows a two-click point-to-point workflow: activate Move, click a vertex, edge point, edge midpoint, face point, face center, or Body center as the base, then click the same inference types on another element to place that exact base point there. These object inferences are active in the default grid mode and the lines mode; Off disables them. Snapped feedback names the inference in Korean (꼭짓점, 선 중점, 선 위, 면 중심, 면 위, 요소 중심). Hold Alt while choosing the destination to bypass inference snapping for deliberate free movement or overlap. In the floor plan, the Move action intentionally uses the 2D-owned placement overlay and plan snapping instead of mounting the 3D base-point tool.',
  '- Body Move evaluates only inference candidates belonging to the visible Body face under the pointer and inside a 16 CSS-pixel screen aperture, then applies strict priority: endpoint > midpoint/center (edge midpoint, face center, or Body center) > edge > face. Hidden or occluded topology cannot steal the pointer, a closer lower-tier candidate never beats an eligible higher tier, and a higher-tier candidate outside the aperture never steals the pointer. Base and destination use the same rule; feedback uses one constant 8px screen-space square for every type, colored green for endpoints, cyan for midpoint/center, red for edges, and blue for faces, while Korean labels and the persistent base/live target remain visible.',
  '- Body Rotate uses the shared pivot state machine in both 3D and the floor plan: place the pivot, place the reference arm, then set the angle. It updates the Body topology as a preview and commits one undo step while preserving persistent topology ids, materials, and UV frames. Escape or cancel restores the original selection and clears the action.',
  '- Body Scale uses the existing six linear-resize handles in 3D: activate Scale, drag one X/Y/Z side handle, and keep the opposite face fixed while grid snapping and the existing HUD report the live dimension. Scale is one-axis-at-a-time, preserves topology ids/materials/UV frames, keeps the preview ephemeral, commits one undo step, and Escape or cancel restores the original selection and clears the action. Body Rotate uses the shared pivot state machine around X, Y, or Z in 3D; the floor plan remains Y-only.',
  "- Body Push/Pull is an explicit 3D face operation and is intentionally omitted from the floor-plan action menu: activate it from the 3D Body action menu, click a valid face, and the existing drag begins immediately after that face click. It accepts only the selected Body face, keeps distance previews ephemeral, commits one undo step, and clears the armed action on commit or cancel. Cursor distance is the dot product of cursor minus the face anchor with the unit face normal, so the cursor spatial relation to the face normal determines the sign rather than screen left/right. In Lines mode, semantic object snapping resolves other elements' faces, edges, and points while excluding the active Body; Grid quantizes the scalar distance and Off follows the raw cursor. Shift (tap) cycles the existing structural polygon snapping HUD through Grid, Lines, and Off; it never bypasses snapping. Typed distances use the shared unit-aware length input: preserve the live cursor sign and apply the typed positive magnitude. If a rejected preview is invalid, clear the live override and current distance, remain in the armed action, and require a later valid preview before commit.",
  '- Body Offset is an explicit 3D face operation and is intentionally omitted from the floor-plan action menu. Its exact action sequence is: select the Body, click Offset in the existing floating 3D action menu, click an eligible planar line-edged face, move perpendicular to the nearest clicked profile edge in the face plane, then click or press Enter to commit. The canonical sign is `distance > 0` outward and `distance < 0` inward; exterior is positive and interior is negative regardless of loop winding. The shared unit-aware input accepts a signed metre or imperial value, with an explicitly typed sign authoritative over the live cursor sign. Execute preview and commit through the same core operation from the same original Body and input: the ephemeral preview equals the committed result. A successful gesture commits one topology update and one undo step. A rejected preview clears only the live override and remains armed; Escape or cancel, tool switch, selection loss, and unmount clear the preview and action while leaving scene and history unchanged.',
  '- Body Follow Path is an explicit 3D face operation and is intentionally omitted from the floor-plan action menu: activate it from the 3D Body action menu, click an eligible planar convex line-edged face, click successive Body-local path stations, and commit an open path with Enter or click and a closed path by repeating the first station or pressing C. The first station lies on the profile plane and the first segment follows the profile normal. Use the shared snapping scope, Alt raw bypass, typed length input, live preview, Escape cancellation, one topology update, one undo step, and atomic invalid-preview rejection. The resulting baked sweep renders in the floor plan, but the floor plan has no sweep edit affordance.',
  '- Face imprint accepts only a planar line-edged closed face with no existing inner loops; the profile must be coplanar, strictly inside, non-self-intersecting, and must not touch the boundary. It preserves existing half-edge ids/materials/UV frames and gives the inset/reveal faces deterministic ids.',
  '- Programmatic agents do not simulate pointer gestures. Express the same final state with deterministic operations and explicit coordinates.',
  '',
  '## Design Ontology',
  '',
  '1. Read `pascal://ontology/manifest` before relying on ontology-backed classification; the manifest pins Pack id `pascal-architecture-core`, semantic version `1.0.0`, MIT license, and artifact hashes.',
  '2. Use `query_design_ontology` for bounded class, allowed-operation, relationship, and evidence lookup. Use `explain_design_rule` for an evidence-backed rule such as `pascal:rule/window-hosted-by-wall`.',
  '3. Treat BOT, IFC, and bSDD identifiers as mappings only. Pascal ids and the Pack/class/version semantic ref are the stable execution boundary.',
  '4. For a Window, resolve the actual host Wall from the scene before applying an opening operation. If the ontology pack is unavailable or invalid, keep existing modeling operations available and do not mutate scene JSON or history as part of ontology lookup.',
  '5. Internal AI requests carry semantic refs only for selected nodes. Do not copy the ontology graph into an AI prompt; query the MCP surface when evidence or relationships are needed.',
  '',
  '## Completion Check',
  '',
  '- The requested geometry exists at the intended dimensions and hierarchy.',
  '- `validate_scene` succeeds and `verify_scene.hasIssues` is false, or remaining limitations are stated precisely.',
  '- The mutation is visible in the editor and undo restores the prior state when the operation is undoable.',
  "- External agents return the final `editorUrl`; the internal agent returns a concise message in the user's language plus the smallest valid patch set.",
  '',
  '## Keeping This Manual Current',
  '',
  'Any change that adds or changes a modeling operation, MCP tool/resource/prompt, node capability, interaction modifier, unit rule, validation rule, or AI control path must update this manual in the same change. Remove obsolete instructions instead of accumulating compatibility advice. Tests must prove that both the MCP resource and the internal modeling prompt still expose the current manual.',
].join('\n')
